using UnityEngine;
using UnityEngine.UI;
using UnityEngine.EventSystems;

public class TimeSliderController : MonoBehaviour, IPointerDownHandler, IPointerUpHandler
{
    [Header("R√©f√©rences")]
    public ShipCSVPlayer player;
    public Slider timeSlider;

    [Header("Options")]
    public bool isInteractive = true;

    private bool userDragging = false;
    private bool initialized = false;
    private float maxTime = 0f;
    private float previousTimeScale = 1f;
    
    [Header("Play / Pause")]
    public Button playPauseBtn;

    private bool isPaused = false;
    public bool IsDragging => userDragging;
    
    
    void Start()
    {
        if (playPauseBtn != null)
            playPauseBtn.onClick.AddListener(TogglePlayPause);
    }


    void Update()
    {
        if (player == null || timeSlider == null) return;

        // üîµ Initialisation diff√©r√©e (CSV charg√©)
        if (!initialized && player.GetLastFrameTime() > 0f)
        {
            maxTime = player.GetLastFrameTime();
            timeSlider.minValue = 0f;
            timeSlider.maxValue = maxTime;
            initialized = true;
        }

        if (!isInteractive || !initialized) return;

        // üîµ Update automatique si pas en drag
        if (!userDragging)
        {
            timeSlider.value = player.GetElapsedTime();
        }
        else
        {
            // üü† En mode drag, on met √† jour manuellement
            player.SetElapsedTime(timeSlider.value);
        }
         // --- Pause/reprise avec ESPACE ---
        if (Input.GetKeyDown(KeyCode.Space))
        {
            TogglePlayPause();
        }
    }

    // ============================================================
    //                    GESTION DU DRAG
    // ============================================================
    public void TogglePlayPause()
    {
        isPaused = !isPaused;

        if (isPaused)
        {
            previousTimeScale = Time.timeScale;
            Time.timeScale = 0f;
            Debug.Log("‚è∏ Pause activ√©e");
        }
        else
        {
            Time.timeScale = previousTimeScale != 0 ? previousTimeScale : 1f;
            Debug.Log("‚ñ∂ Lecture reprise");
        }
    }



    public void OnPointerDown(PointerEventData eventData)
    {
        if (!initialized) return;

        userDragging = true;

        // üü• Freeze total de la sc√®ne
        previousTimeScale = Time.timeScale;
        Time.timeScale = 0f;

        Debug.Log("‚è∏ Scene FREEZED (drag)");
    }

    public void OnPointerUp(PointerEventData eventData)
    {
        if (!initialized) return;

        userDragging = false;

        // üü© D√©freeze
        Time.timeScale = previousTimeScale;

        // force la position finale
        player.SetElapsedTime(timeSlider.value);

        Debug.Log("‚ñ∂ Scene UNFREEZED");
    }
}
